version: '2'
services:
	#생성 할 container 이름을 지정 합니다.
	mariadb:
		#container 생성시 사용 할 이미지 지정
		image: mariadb
		# 컨테이너에 볼륨을 마운트 할 때에 사용 됩니다. (host:container)
		# 마운트는 컴퓨터 과학에서 저장 장치에 접근할 수 있는 경로를 디렉터리 구조에 편입시키는 작업을 말한다
		volumes:
			- ~/data/maria:/var/lib/mysql
		restart: always
		# 호스트 포트:컨테이너포트
		ports:
			- "3306:3306"
		#build 옵션
		# dockerfile에 명시된 FROM의 image를 사용하여 위에 명시된image 이름과 tag로 새로운 image를 생성 합니다.
		build:
			#dockerfile의 위치를 지정 합니다.
			context: ./requirements/mariadb
			dockerfile: Dockerfile
		# l70 아래에 정의되어있는 네트워크를 사용
		networks:
			inception:
		env_file: .env

	wordpress:
		depends_on:
			- mariadb
		image: wordpress
		volumes:
			- ~/data/wordpress:/var/www/wordpress
		restart: always
		ports:
			- "9000:9000"
		build:
			context: ./requirements/wordpress
			dockerfile: Dockerfile
		networks:
			inception:
		env_file: .env

	nginx:
		image: nginx
		restart: always
		depends_on:
			- wordpress
		ports:
			 - "443:443"
		volumes:
			- ~/data/wordpress:/var/www/wordpress
		build:
			context: ./requirements/nginx
			dockerfile: Dockerfile
		networks:
			inception:
		env_file: .env

volumes:
	mariadb:
		driver: local
		 # - driver: 볼륨을 생성할 때 사용될 드라이버를 설정한다. 어떠한 설정도 하지않으면 local 로 지정된다.
		driver_opts:
			o: bind
			type: none
			device: ~/data/maria
	wordpress:
		driver: local
		driver_opts:
			o: bind
			type: none
			device: ~/data/wordpress

networks:
	inception:
		driver: bridge
		# 기본 네트워크 드라이버입니다. 드라이버를 지정하지 않으면 생성 중인 네트워크 유형이 됩니다. 브리지 네트워크는 일반적으로 통신이 필요한 독립 실행형 컨테이너에서 애플리케이션을 실행할 때 사용됩니다.
